# Generated by Django 3.2.4 on 2021-06-25 10:37

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('para_1', models.TextField()),
                ('para_2', models.TextField()),
                ('para_3', models.TextField()),
                ('picture', models.ImageField(upload_to=home.models.user_directory_path)),
            ],
        ),
    ]
